### ISSUE TITLE
migrate scripts do not work on non-string values

### ISSUE THREAD

**Issue by stockholmux** [piiojs/redis-utils#1]
The migrate scripts only work on Redis string type values. Any other type will yield a `null` in the JSON and data loss. (Also the script calls them 'hashes' which is incorrect).

Example:
```
$ redis-cli
> flushdb
OK
> hset Foo bar 1
(integer) 1
```

```
$ ./download.js

*********** START SCANNING FOR PATTERN * ***********

Found 1 keys on this round. Round count: 1
Getting values
Got 1 values
Write hashes to file

*********** SCAN FINISHED ***********

Number of rounds: 1
Number of hashes found: 1
Filename: dump.json
Execution time: Less than a second
$ tail dump.json
[{"Foo":null}]
```

**Comment by cachila** [comment]
Hi Kyle, thanks for posting this issue.

What happened here is a misunderstanding. On our particular system, we call the keys on Redis 'hashes' and it is a bit unhappy to call it that way on an open source code. I will update this ASAP.

Regarding the actual Redis Hash, I'm afraid this code will not work as it is. Feel free to adapt it and make a pull-request.

**Comment by cachila** [comment]
Kyle just for FYI I have just updated the code so it doesn't contain the 'hashes' word.
